<a href="https://colab.research.google.com/github/ATechievision/DataHubArchana/blob/main/Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def addition(a,b): #for the sum of tow values
 return a+b

def subtraction(a,b): # for the difference of a & B
  return a-b

def multiplication (a,b): # for the product of a & b
  return a*b

def division (a,b): # for the division of a & b
  return a/b


In [ ]:
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))


if a>b:
  print("A=",a,"is greater")
else:
  print("B=",b," is greater")

Enter the first number: 15
Enter the second number: 20
B= 20  is greater


Write a number to check whether the given number is an armstrong number or not.

Armstrong number is the number whose sum of cube of its digits is equal to the number.
153 1,5,3 are the digits
1^3=1
s^3=125
3^3=9
1+125+27=153


In [ ]:
num = int(input("Enter a number: "))
sum = 0

temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3  3 cube of the number
   temp = temp //= 10

if sum == num:
   print(num,"is an Armstrong number")
else:
    print(num,"is not an armstrong number")

SyntaxError: invalid syntax (<ipython-input-29-6600399b1b93>, line 7)

In [ ]:
#Write a program to check a number is a prime number or not.


# Prime number is  no. which is divisible by 1 and only itself.
#e.g.- 2,3,5,7, 11.13- all these numbers are divisible by 1 or itself .So,they are prime numbers.
# 4,6,8,9 -These are not prime numbers


num = int(input("Enter a number: ")) #11


if num >1: # 11>1 --yes
   for i in range(2,num):   #2,3,....,10
     if (num % i) == 0: #11 %2 ==1
       print(num,"is not a prime number.")

       break
     else:
       print(num,"is a prime number.")
       break
else:
  print(num,"is not a prime number.")

Enter a number: 11
11 is a prime number.


In [ ]:
#Create a calculator program for addition, subtraction, multiplication and floor division.
# Take the inputs from the user , an based on the choice og operation.

a= int(input ("Enter the first no. :"))
b= int(input ("Enter the second no. :"))
c= input("Enter the operation you want to perform(+,-,*,/):")

print(a)
print(b)

def addition(a,b):
 return a+b

def subtraction(a,b):
 return a-b

def multiplication(a,b):
  return a*b

def division(a,b):
  return a//b

  n1 = int(input("Entert 1st number:"))
  n2 = int(input("Enter 2nd number:"))

  choice = input("Enter your choice of operation (+,-,*,/):")

  if (choice =="add" or choice == "Add" or choice =="addition" or choice =="Addition" or choice == "+"):
     res=addition(n1,n2) #res-result
  print("Addition of the numbers : ",res)

  elif (choice =="sub" or choice =="Sub" or choice =="subtraction" or choice =="Subtraction" or choice== "-"):
     res=subtraction(n1,n2)
  print("Subtraction of the numbers : ",res)

  elif (choice =="mul" or choice == "Mul" or choice =="multiplication" or choice =="Multiplication" or choice == "*"):
     res=multiplication(n1,n2)
     print("Multiplication of the numbers : ",res)

  elif (choice =="div" or choice == "Div" or choice =="division" or choice =="Division" or choice == "/"):
     res=division(n1,n2)
     print("Division of the numbers : ",res)

else:
  print("Invalid operation")

# if c == '+':
#   print(addition(a,b))
# elif c == '-':
#   print(subtraction(a,b))
# elif c == '*':
#   print(multiplication(a,b))
# elif c == '/':
#   print(division(a,b))

SyntaxError: invalid syntax (<ipython-input-50-0cd1c21c2d0e>, line 32)

In [ ]:
# Write a program to create a fibonacci sequence using python if else statements.
#The next term is the sum of the last two
#0,1,1,2,3,5,8......upto any term


nterms = int (input("Enter the number of terms:"))

n1,n2 = 0,1
count = 0

if nterms <= 0:
  print("Enter a positive number.")
elif nterms ==1:
  print("Fibonacci sequence upto", nterms,":")
  print(n1)
else:
  print("Fibonacci sequence:")
  while count< nterms:
    print(n1)
    nth = n1 + n2
    n1 = n2
    n2 = nth
    count += 1




Enter the number of terms:10
Fibonacci sequence:
0
1
1
2
3
5
8
13
21
34


In [ ]:
#Write a program to find factorial of a number.

num = int(input("Enter a number: "))

In [ ]:
#Write a program to check a number is odd or even.
#even numbers divisible by 2 ,remainder--0
#odd numbers not divisble by 2,remainder--1

num = int(input("Enter a number: "))

if num%2==0:
  print("The number is even.")
else:
  print ("The number is odd.")


Enter a number: 5
The number is odd.


In [ ]:
#Create a nested deictionary with vaues as nested list for each key in the dictionary.

#nested_dictionary

nested_dict = {
    'key1': [[1,2,3], [4,5],6],
    'key2': [["a","b"], "c", "d"],
    'key3': [[True,False]]
}

nested_dict

print(type(nested_dict))

<class 'dict'>


In [ ]:
#Cretae two sets and perform the following:
#a. Union of he twosets
#b.Intersection of the two sets


#Set- Is an unordered collection of data i.e, unique.

#{}-curley braces for creating a set.
# set1 = {1,2,3,4}

set1 = {1,2,3,4}
set2 = {3,4,5,6}

union_set = set1 | set2
print(union_set)

intersection_set = set1 & set2
print(intersection_set)

#INTERSECTION will returna new set containing only the common values.

print(set1.union(set2)) #union of a & b,union operator,checks for unique values,unique os those two sets
print(set1.intersection(set2)) #intersection of a & b

set3 = {"ram", "Shyam", "ram" , "alex"}
print(set3)


list4 = [1,2,2,3,4,4,5,6]
set4 = set(list4) # converting list into set with the help of set()
print(set4)



{1, 2, 3, 4, 5, 6}
{3, 4}
{'Shyam', 'alex', 'ram'}
{1, 2, 3, 4, 5, 6}


In [ ]:
# Create two sets and return the union  and intersection of those two sets.


x = {"a","b","c","d","a","d"}
y = {"c","d","e","f","f","g"}

print(x.union(y))
print(x.intersection(y))


{'c', 'a', 'd', 'b', 'f', 'g', 'e'}
{'c', 'd'}


In [ ]:
set_1={2,5,3,6,True,False}
set_2={1,0,"Archana", "Manasa","Atul",5,3}

set_1.union(set_2)
set_1.intersection(set_2)

{False, True, 3, 5}

In [ ]:
#Create a nested tuple from the dictionary, with each item in the tuple a key value pair form the dictionary.
# nested_tuple = (
#     {'key1':1},2,3, (4,5),6),
#     {'key2': "a"},"b", "c", "d"),
#     {(True, False)
# )

# print(nested_tuple)


dict1 = {
    "key1" : "archana" ,
    "key2" : "manasa"
}

dict2 = {
    "key3" : "x" ,
    "key4" : "y"
}

dict3 = {
    1 : dict1 ,
    2 : dict2
}

nested_tuple= tuple((key,value) for key, value in dict3.items())
print(nested_tuple)

# print(dict3.items)
# for key,value in dict3.items():
#   print(key,value)


((1, {'key1': 'archana', 'key2': 'manasa'}), (2, {'key3': 'x', 'key4': 'y'}))
<built-in method items of dict object at 0x7dcd0313ddc0>
1 {'key1': 'archana', 'key2': 'manasa'}
2 {'key3': 'x', 'key4': 'y'}


In [ ]:
#create a list of 50 even natural numbers, and perform the following operations.

# num = int(input("Enter a number: "))

# if num%2==0:
#   print("The number is even.")
# else:
#   print ("The number is odd.")

# list_1 = []

# for i in range(1,101):
#   if i%2==0:
#     list_1.append(i)
# print(list_1)

list2 = [i for i in range(2,102,2)]
print(list2)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [ ]:
# list3 = [2*i for i in range(1,51)]
# print(list3)
# count= len(list3)
# print("No. of elements in the list:",count)

# reversed_list = list3[::-1]
# print(reversed_list)

# #Sort the list in ascednding order

# ascending_order = sorted(list3)
# print(ascending_order)

#Descending order

# descending_order = sorted(list3, reverse=True)
# print(descending_order)

#index
index_44 = list3.index(44)
print(index_44)

21


In [ ]:
index_10 = list3.index(10)
print(index_10)

4


In [ ]:
print(list3.index(20))

9


In [ ]:

list3[index_44] = 100
print(list3)



[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 100, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [ ]:
squared_list = [num**2 for num in list3]
print(squared_list)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 10000, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604, 10000]


#For the given strings A= "Python programming language" , B = "Best in the World",perform the following operations.
#Using indexing operations, get the text "gram" rom the string A.
#Using indexing operations ,get the text "World" from the string B.
#Change the letters in both strings to uppercase letters.
#Concatenate the two strings.

In [ ]:
A = "Python Programming Language"
B = "Best In The World"
print(A)
print(B)



Python Programming Language
Best In The World


In [ ]:
A[10:14]

'gram'

In [ ]:
B[-5:]

'World'

In [ ]:
B[-9:-6]

'The'

In [ ]:
A.upper()
B.upper()

'BEST IN THE WORLD'

In [ ]:
conC = A + " ," + B
print(conC)

Python Programming Language ,Best In The World


#Create a list with n numbers, and using negative indexing return the list starting from the 5th
index to the n-2th index.
#Using range() , create a list with numbers ranging from 5-100, and the number of elements should be exactly 19..
range (starting_index : ending_index : step_/size)

In [ ]:
#Count the number of elements in the list


NameError: name 'count' is not defined

In [ ]:
#Single Inheritence
#before defining a class we have to give the class name
#Single Inheritence
#before defining a class we have to give the class name

class Parent:
  def __init__(self):
    self.name = "XYZ"

class Child(Parent):
  def display(self):
    print(self.name)

obja= Child()
obja.display()
class Child(Parent):
  def display(self):
    print(self.name)

obja= Child()
obj1.display()



XYZ


NameError: name 'obj1' is not defined

In [ ]:
class Animal:
  def sound(self):
    print("Animals make sound")

class Dog(Animal):
  def bark(self):
    print("Dog barks")


obj2=Dog()
obj2.bark()
obj2.sound()


Dog barks
Animals make sound


In [ ]:
#Multiple Inheritance-- Inheriting from more than one class


class parent1:
  def__init__(self):
    self.name1 = "Archana"

class Parent2:
  def_init_(self):
    self.age=20
    self.city="Almere"

class child(Parent1, Parent2):
  def_init_(self):
    self.country ="Netherlands"

    Parent1._init(self)
    Parent2._init_(self)

  def display(self):
    print(self.name1, self.age , self.city, self.country)

 obj3= child()
 obj3.display()
 obj3.display()


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 23)

In [ ]:
#Multilevel Inheritence-> We have one parent that parent have one child class and  the child class also havwe it's own sub child class.

#A > B > C

class A:
  def_init_(self):
    self.name = "XYZ"

class B(A):
  def_init(self):
    self.age = 20

    A._init_(self)

  def display(self)
  print(self.name, self.age)

class C(B):
  def_init(self)
    self.city = "Bangalore"

    B._init_(self)

  def display2(self):
    print(self.name, self.age , self.city)

obj =C()

obj1 =B()

obj1.dispaly()
obj.display2



In [ ]:
class Parent:
  def __init__(self):
    self.mobile_brand = "Apple"

class Child1(Parent):
  def __init__(self):
    self.mobile_name1 = "IPhone 15"

    Parent.__init__(self)-could you fix the error
    print(self.mobile_brand, self.mobile_name1)


class Child2(Parent):
  def __init__(self):
    self.mobile2_name = "IPhone 14"

    Parent.__init__(self)

  def display2(self):
    print(self.mobile_brand, self.mobile2_name)


obj1 = Child1()

obj2 = Child2()

obj2.display2()
class Child1(Parent):
  def_init_  (self):
    self.mobile_name1 = "IPhone 15"

    Parent._init_(Self)
    print(self.mobile_brand, self.mobile1_name)


class Child2(Parent):
  def_init_(self):
    self.mobile2_name = "IPhone 14"

    Parent._init_(self)

  def display2(self):
    print(self.mobile_brand.self.mobile_name)


obj1 = Child1()

obj2 = Child2()

obj2.display2()


SyntaxError: invalid syntax (<ipython-input-16-641a3339c580>, line 36)

#Create a parent class as person and define some attributes here name, address, and define display().

#Create a child class, define age, inherit parent class and display
#define another child2 class, define name2 and inherit parent class here.
#define one more class and you have to inherit both child1 and child2.


In [ ]:

class Person:
def_init_(self):
  self.name = "XYZ"
  self.country = "Holland"

def display(self):
  print(self.name, self.country)

class child1(Person):
  def_init_(self):
    self.age = 28

    Person._init_(self)

  def display1(self):
    print(self.name, self.age, self.country)

class child2(Person):
  def_init_(self):
    self.name2 = "ABC"

    Person._init_(self)

  def display2(self):
    print(self.name, self.name1)

class subchild(child1, child2):
  def_init_(self):


    child1._init_(self)
    child2._init_(self)



 def display4(self):
  print(self.name2, self.age, self.name, self.country)


obj1 = child1()

obj2 = child2()

obj3 = subchild()

obj1.display1()
obj2.display2()
obj3.display4()



IndentationError: unindent does not match any outer indentation level (<tokenize>, line 36)

Encapsulation- It is a type of object oriented programming concept(OOPS) in which we restrict the direct access of an object's components.

#Why Encapsulation->( it will help us for data protection)Data protectation.data hiding, code maintainability.


In [ ]:
#In the bank account ,we have a/c no.,balance-->I want to put a restriction ,so I can only have access to it.
#Access ZModifiers :
#Public --->that is accessible outside the class and inside the class also.(Public Access Modifiers)

#Protected ---> It is accessible to next derived class.
#But in Python Protected and Public are same.
#It will be declared with the help of "_" before the name.

#Private--> It is only accessible inside the class.
#It is declared with the help of "__"(double underscore) before the name.




In [ ]:
class myClass:
  def __init__(self,color):
    self.color = color  #publicaccess modifier

  def display(self) :
    print(self.color)

class class2(myClass):
  def __init__(self):
    myClass.__init__(self,"")

  def display2(self):
    print(self.color)

obj = myClass("red")

obj2 = class2()

obj2.display2()
  def display():
    print(self.color)

class class2(myClass):
  def_init_(self):
    myClass._init_(self)

  def display2(self):
    print(self.color)

obj = myClass("red")

obj2 = class2()

obj2.display2()

IndentationError: unexpected indent (<ipython-input-28-42a99ae65d36>, line 20)

In [ ]:
class A:
  def __init__(self, balance):
    self.__private_mem = "This is the private member" #it is a private attribute
    self.balance = balance #public

  def display_1(self):
    print(self.__private_mem,self.balance)

class B(A):
  def display1(self):
    print(self._private_meme, self.balance)

obj1 = A(1000000)
obj1.display_1()

  def display_1 (self):
    print(self.__private_mem,self.balance)

class B(A):
  def display1(self):
    print(self._private_meme, self.balance)

# obj1 = A(10,00,000)
# obj.display_1()

obj2 A(12000)
obj2.display_1()


IndentationError: unexpected indent (<ipython-input-31-6f1488d4d203>, line 16)

In [ ]:
class h:
  def __init__(self):
    self.__protected_mem = "This is the protected member" #it is a protected attribute

obj = h()

print(obj._h__protected_mem)



This is the protected member


In [ ]:
class h:
  def __init__(self):
    self.__protected_mem = "This is the protected member" #it is a protected attribute

obj = h()

# Access the protected member as an attribute, not a function
print(obj._h__protected_mem)

This is the protected member


In [ ]:
#Polymorphism--Many forms,i.e, a function or method will hve multiple functionality according to the need.

#e.g- Our mother - She is the wife of my father.
#                - daugter-in-law of my grand parents
#                -She is my mother

#Polymorphism is nothing but just a function behaving differently according to the situation.

In [ ]:
class Mother:
  def work(self):
    print("mother")

class office:
  def work(self):
    print("employee")

class learner:
  def work(self):
    print("learner")

obj1 = learner()
obj1.work()

obj2 = office()
obj2.work()

obj3 = Mother()
obj3.work()

learner
employee
mother


In [ ]:
#Function overriding --when we have same function but different functionalities or replacing some part of  parent class with a child class.

#Method overloading --We have same method and different parameters


class A:
  def function_1(self, a,b):
    return a+b

obj1 = A()
print(obj1.function_1(10,20))
print(obj1.function_1(20,30,40))


# Method overloading is not possible inside Python.

30


TypeError: A.function_1() takes 3 positional arguments but 4 were given

In [ ]:
class animal:
  def sound(self):
    print("animals make sound")


class dog(animal):
  def sound(self):
    print("Dog barks")
obj = dog()
obj.sound()

obj1 = animal()
obj1.animal()

Dog barks


AttributeError: 'animal1' object has no attribute 'animal1'

In [ ]:
#Abstraction--> It is a process of hiding unnecessary or complex information form the user or only want to show the relevant information details to the user.

#Abstract method-With the help of this method ,we perform abstraction in Python.


In [ ]:
from abc import ABC, abstractmethod #importing abstractmethod

class car(ABC)
  def_init_(self, brand, model, year):
    self.brand = brand
    self.model = model
    self.year = year

  @abstractmethod
  def info(self):
    print("Engin is taking fuel and running the car")
    pass

class child(car):
  def info(self):
    print(self.brand, self.model, self.year)


obj1 = child("Audi", "12", 2019)

obj1.info()

obj2 = Car("Nano", "13", 2008)
obj2.info()


SyntaxError: expected ':' (<ipython-input-52-48b28837d367>, line 3)

In [ ]:
from abc import ABC , abstractmethod

class RemoteControl(ABC):
  @abstractmethod
  def turn_on(self):
    pass

  @abstractmethod
  def press_button(self):
    print("How the remote is working")

class TV(Remote RemoteControl):
  def press_button(self):
    print("TV is turned on")

tv = TV()

tv.press_button()

tv1 = RemoteControl()
tv1.press_button()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-56-ab004af75f54>, line 12)

NumPy-Numerical Python.
This is a powerful librarry used for numerical computing.
Arrays:-
Features-
Array vs.NumPy-
NumPy-Faster performance than array
    - NumPy is Multidimensional aarays
    -Mathematical operations
    -Integration-works well with other libraries.
    -
    -

In [3]:
import numpy as np


In [7]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

The Number Of [](square brackets) = dimension of your array

*   List item
*   List item



In [9]:
# Zero dimensional array
#How to create 0-D array

array2 = np.array(55)
print(array2)

print(array2.ndim)---> ndim: to check the dimension of the array


55
0


In [11]:
#How to create 1D array

array3 = np.array([12,24,36,48])

print(array3)
print(array3.ndim)

[12 24 36 48]
1


In [12]:
#code check
arr = np.array([[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]])
print(arr.ndim)

25


In [14]:
#How to create a 2D array


arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [18]:
print(arr.shape) #--->Number of rows and columns, 2 rows and 4 columns

(2, 4)


In [19]:
arr2 = np.array ([[1,2,3],[4,5,6],[6,7,8],[3,7,9]])


print(arr2)

[[1 2 3]
 [4 5 6]
 [6 7 8]
 [3 7 9]]


In [23]:
arr2.ndim



2

In [24]:
arr2.shape #no. of rows and columns

(4, 3)

In [30]:
# How to create  a 3-d array-( if you add 2-2d array you can create a 3-d )


arr3 = np.array([[ [1,2,3], [4,5,6]], [[3,4,5],[2,7,5]]])

print(arr3)

print(arr3.ndim)

print(arr3.shape) #--->(no. of 2-d arrays you will have  no. of rows,no. of  columns)

index-->0th(no. of blocks of 3-d),1st (number of rows in each block),2nd(number of columns in each block),3rd(number of elements in each block),4th(number of elements in each block)

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [2 7 5]]]
3
(2, 2, 3)


In [34]:
#Array Indexing

#--- access the element present in the array by using it's index value
#  Access elements in 1-d array-I want to get element

array1 = np.array ([12,34,45,67,89])

print(array1[3])

67


In [35]:
arr = np.array([[1,2,4],[3,5,8]]) # Access element  in 2-d ,I want to get the element.

print(arr[0,1]) #--->first you will get inside of the row and then you will fetch the index value

2


In [37]:
arr = np.array([[111,22,45],[45,56,78]])
print(arr[1,2])

78


In [39]:
#

arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]]])

print(arr3)
print(arr3[0,1,2])  #---

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]]
6


Array Slicing--

In [42]:
array1 = np.array([18.11,53.34,65.17,78.54,98.35,45.28])
print(array1[2:5])
print(array1[2:6])

[65.17 78.54 98.35]
[65.17 78.54 98.35 45.28]


In [44]:
array2 = np.array ([12,2.2,45,3.5])
print (array2[2:3])

[45.]


In [52]:
# Slicing in 2-d array.
arr = np.array([[1,2,3,4],[3,5,7,8]])
print(arr[0,1:3])#--->first block number and then slicing

[2 3]


In [58]:
#Slicing in 3-d array

arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[6,7,8]]])

print(arr3)

print(arr3.shape)

print(arr3[1,1,1:3]) #---1(1st block),1(row of that perticular block),1:3(from 1 to until 3-it will print from 1th index and 2nd index from that row)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [6 7 8]]]
(2, 2, 3)
[7 8]


#Convert one type array to another

In [62]:
#convert 1-d array to  4-d array

data = [1,2,3,4,5,6,7,8]
arr = np.array(data,ndmin=7)#---> ndmin-is used to convert any dimension
print(arr)
print(arr.ndim) #--->ndim-will give you the dimension

[[[[[[[1 2 3 4 5 6 7 8]]]]]]]
7


# Reshape--> It will change the shape of your array according to rows, and columns

In [66]:
arr = np.array([1,2,3,4,5,6,7,8,9,10]) #-->rows*col = Number of elements

print(arr)
print(arr.reshape(2,5))



[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
