<a href="https://colab.research.google.com/github/ATechievision/DataHubArchana/blob/main/NumPy_hands_on.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#3.Create a 2x2 ,3x3,4x4 identity matrix using numpy.

import numpy as np
a=np.identity(2)
print(a)
b=np.identity(3)
print(b)
c=np.identity(4)
print(c)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#Identity matrix-all the diagonal will be 1 and all the non-diogonal element will be  0.

arr = np.identity(2) # 2x2
print(arr)

arr1 = np.identity(3) # 3x3
print(arr1)

arr2 = np.identity(4)# 4x4
print(arr2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
arr = np.eye(2,3) # pass any shape to create identity matrix
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


In [7]:
# How to decide the shape

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.Create a numpy array with shape 2x5 that has all the elements as zero.


In [10]:
arr = np.zeros((2,5)) # return float values and can be converted into integer using dtype='int'
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# prompt: .Create a numpy array with shape 2x5 that has all the elements as zero.

import numpy as np

arr = np.zeros((2, 5))
arr


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones((2,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
arr = np.ones((2,5))+100
print(arr)

[[101. 101. 101. 101. 101.]
 [101. 101. 101. 101. 101.]]


In [14]:
arr = np.ones((2,5))+1
print(arr)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# reshaped_arr = arr.reshape(2,6)
# print(reshaped_arr)

# reshaped_arr = arr.reshape(2,3,2)
# print(reshaped_arr)

reshaped_arr = arr.reshape(13,1)
print(reshaped_arr)

# reshaped_arr = arr.reshape(2,6)
# print(reshaped_arr)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [29]:
#Create a numpy array that has the shape 3x5 and all the elements are 5.

arr1 = np.ones((3,5), dtype= 'int') + 4 # if I don't give the data type int ,it will return float values.
print(arr1)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [28]:
arr = np.full((3,5),5)
print(arr)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [32]:
# 6.Create a numpy array with random integer in the range 0 to 100, and the sample size should be 25.

arr = np.random.randint(0,100,size=25)
print(arr)

[97 13 12 90 91 58 86 56 92 79 98  0 68  0 13 35 82 70 27 17 16 69 42 74
 69]
